"""add_server_defaults

Revision ID: 7f50efcab8fd
Revises: 
Create Date: 2026-04-21 16:54:24.207536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7f50efcab8fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- HATAYA NEDEN OLAN KISITLAMA DEĞİŞİKLİKLERİ İPTAL EDİLDİ ---
    # op.drop_index(op.f('uq_sevkiyat_kalemleri_sevkiyat_siparis_kalemi'), table_name='sevkiyat_kalemleri')
    # op.create_unique_constraint('uq_sevkiyat_kalemi_plan_siparis_kalem', 'sevkiyat_kalemleri', ['sevkiyat_id', 'siparis_kalemi_id'])
    # op.drop_constraint(op.f('fk_sk_sevkiyat_plani'), 'sevkiyat_kalemleri', type_='foreignkey')
    # op.create_foreign_key(None, 'sevkiyat_kalemleri', 'sevkiyat_planlari', ['sevkiyat_id'], ['id'])

    # --- TESTLERİN GEÇMESİ İÇİN GEREKLİ OLAN EKSİK TARİH GÜNCELLEMELERİ ---
    op.alter_column('markalar', 'olusturma_tarihi', existing_type=sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('kategoriler', 'olusturma_tarihi', existing_type=sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('urunler', 'olusturma_tarihi', existing_type=sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lotlar', 'olusturma_tarihi', existing_type=sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('depolar', 'olusturma_tarihi', existing_type=sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('raflar', 'olusturma_tarihi', existing_type=sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('paletler', 'olusturma_tarihi', existing_type=sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'))

    # --- ALEMBIC'IN BULDUĞU DİĞER DEĞİŞİKLİKLER (İPTAL EDİLDİ) ---
    # op.drop_index(op.f('idx_yerlestirme_gorevleri_depo_id'), table_name='yerlestirme_gorevleri')
    # op.drop_index(op.f('ix_yg_fifo'), table_name='yerlestirme_gorevleri')
    # op.create_index(op.f('ix_yerlestirme_gorevleri_atanma_tarihi'), 'yerlestirme_gorevleri', ['atanma_tarihi'], unique=False)
    # op.create_index(op.f('ix_yerlestirme_gorevleri_depo_id'), 'yerlestirme_gorevleri', ['depo_id'], unique=False)
    # op.create_index(op.f('ix_yerlestirme_gorevleri_durum'), 'yerlestirme_gorevleri', ['durum'], unique=False)
    # op.create_index(op.f('ix_yerlestirme_gorevleri_id'), 'yerlestirme_gorevleri', ['id'], unique=False)
    # op.create_index(op.f('ix_yerlestirme_gorevleri_olusturma_tarihi'), 'yerlestirme_gorevleri', ['olusturma_tarihi'], unique=False)
    # op.create_index(op.f('ix_yerlestirme_gorevleri_oncelik'), 'yerlestirme_gorevleri', ['oncelik'], unique=False)
    # op.alter_column('zonlar', 'aciklama', existing_type=mysql.TEXT(), nullable=False)
    # op.alter_column('zonlar', 'sira', existing_type=mysql.INTEGER(), nullable=False, existing_server_default=sa.text("'0'"))
    # op.alter_column('zonlar', 'aktif', existing_type=mysql.TINYINT(display_width=1), nullable=False, existing_server_default=sa.text("'1'"))
    # op.alter_column('zonlar', 'olusturma_tarihi', existing_type=mysql.DATETIME(), nullable=False, existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.create_index(op.f('ix_zonlar_id'), 'zonlar', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade içeriğini de hatasız geri dönüş yapabilmek adına temizledik.
    # ### end Alembic commands ###
